---
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/generate":
    post:
      summary: Generate
      operationId: generate_generate_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/GenerateRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    GenerateRequest:
      properties:
        query:
          type: string
          title: Query
        context:
          type: string
          title: Context
          default: ''
        llm:
          type: string
          title: Llm
      type: object
      required:
      - query
      - llm
      title: GenerateRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            "$ref": "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
