---
openapi: 3.1.0
info:
  title: Ingestor API
  version: 0.1.0
paths:
  "/upload":
    post:
      summary: Upload File
      operationId: upload_file_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
              required:
                - file
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  "/search":
    get:
      summary: Search
      operationId: search_search_get
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: top_k
          in: query
          required: false
          schema:
            type: integer
            default: 3
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    UploadResponse:
      type: object
      properties:
        message:
          type: string
        chunks:
          type: integer
      required:
        - message
        - chunks
      title: UploadResponse
    SearchResponse:
      type: object
      properties:
        query:
          type: string
        results:
          type: array
          items:
            type: string
      required:
        - query
        - results
      title: SearchResponse
    Error:
      type: object
      properties:
        error:
          type: string
      required:
        - error
      title: Error
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
